#!/bin/bash

# 判断参数个数是否正确
if [ $# -ne 1 ]; then
    echo "Usage: $0 <you_elf>"
    exit 1
fi

# 保存 ELF 文件名
elf_file="$1"

# 检查 ELF 文件是否存在
if [ ! -f "$elf_file" ]; then
    echo "Error: File '$elf_file' not found."
    exit 1
fi

# 启动 socat 并监听端口
socat tcp-listen:12345,reuseaddr,fork EXEC:"$elf_file",pty,raw,echo=0

